image:
  name: fedora:34
  entrypoint: [ '/bin/bash', '-c' ]

stages:
  - qa

lint:
  stage: qa
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - gitlab-org
  script:
    - dnf -y install pip
    - pip install ansible-lint
    - ansible-lint -q .
  allow_failure: true
